COMPONENT=BigBrotherAppC
#TINYOS_NP=BNP

CFLAGS += -I$(TOSDIR)/lib/net \
          -I$(TOSDIR)/lib/net/le \
          -I$(TOSDIR)/lib/net/ctp \
		  -I../include \
		  -I../lib/Infrared \
		  -I../lib/SensorHandler \
		  -I../lib/TimeSync

#PFLAGS += -I /opt/tinyos-2.x-contrib/ethz/snpk/tos/lib/dsn -DUSART=1 \
		  -DTIMESYNC_RATE=3


#					-DRAW_DUMP
include $(MAKERULES)

