function drawtime(timeslot)

[day,dow] = weekday(timeslot,'long');
text(340,50,dow,'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'FontSize',12, 'Color', 'r');
text(550,50,datestr(timeslot),'VerticalAlignment','middle',...
    'HorizontalAlignment','center',...
    'FontSize',12, 'Color', 'r');

